"""Add emoji field to wishlists

Revision ID: 16a8d208d854
Revises: 55f9468e75ed
Create Date: 2025-11-23 22:25:38.635281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a8d208d854'
down_revision = '55f9468e75ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlists', sa.Column('emoji', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishlists', 'emoji')
    # ### end Alembic commands ###
