"""Update item model fields and status enum

Revision ID: 171233f15090
Revises: 1a87e91ac8e5
Create Date: 2025-11-23 22:11:40.687174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171233f15090'
down_revision = '1a87e91ac8e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist_items', sa.Column('link', sa.String(length=1000), nullable=True))
    op.add_column('wishlist_items', sa.Column('image_url', sa.String(length=1000), nullable=True))
    op.drop_column('wishlist_items', 'main_image_url')
    op.drop_column('wishlist_items', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist_items', sa.Column('url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('wishlist_items', sa.Column('main_image_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_column('wishlist_items', 'image_url')
    op.drop_column('wishlist_items', 'link')
    # ### end Alembic commands ###
